
[server]
headless = true
address = "0.0.0.0"
port = 7860
enableCORS = false
enableWebsocketCompression = false

[theme]
primaryColor = "#2563EB"
backgroundColor = "#FAFBFC"
secondaryBackgroundColor = "#F8FAFC"
textColor = "#1E293B"
font = "sans serif"
